sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 3567dmma
  alioss:
    endpoint: oss-cn-qingdao.aliyuncs.com
    access-key-id: LTAI5tBPY426JNAEwDCmay9g
    access-key-secret: UpNv7iWgtFkuNSo4Yq4OSkah3oliMZ
    bucket-name: my-web--tlias